import '@shopify/polaris/build/esm/styles.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Page, PolarisProvider } from '~/components/polaris'
import { SubmitButton } from '~/components/submit'
import { isAuthenticated } from '~/lib/auth'
import { getGraphqlClient } from '~/lib/shopify'
import { logout } from './actions'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={'mx-auto max-w-7xl px-4 py-12'}>
          <PolarisProvider>
            {isAuthenticated() ? <LoggedIn>{children}</LoggedIn> : children}
          </PolarisProvider>
        </div>
      </body>
    </html>
  )
}

async function LoggedIn({ children }: React.PropsWithChildren) {
  const client = getGraphqlClient()
  const response = await client.request(`
  query { 
    shop {
      name
      currencyCode
      checkoutApiSupported
      taxesIncluded
      resourceLimits {
        maxProductVariants
      }
    }
  }
  `)

  return (
    <Page
      title={response.data.shop.name}
      secondaryActions={
        <form action={logout}>
          <SubmitButton variant="primary" submit>
            Logout
          </SubmitButton>
        </form>
      }
    >
      {children}
    </Page>
  )
}
